### ISSUE TITLE
front-end does not deal properly with races data on backend

### ISSUE THREAD

**Issue by medhatelmasry** [plan-your-vote/plan-your-vote-cda#71]
Although races can be sorted on the backend, the front end does not reflect these changes

**Comment by ryanliang88** [comment]
There's several issues with respect to races. The races retrieved from the back-end may be still hard coded.

Bug: Currently selecting Vice President adds +1 to the School Trustee.

(Move this comment's issues to an appropriate location)

**Comment by medhatelmasry** [comment]
This is resolved
