### ISSUE TITLE
social media icons in footer

### ISSUE THREAD

**Issue by medhatelmasry** [plan-your-vote/plan-your-vote-cda#75]
Social media icons are not being dynamically pulled from back-end in the footer.

Also,  social media icons are not linked to anything

**Comment by ryanliang88** [comment]
Images for the icons need to be stored as well.

**Comment by medhatelmasry** [comment]
Rys Rabang displayed social media icons by reading API. Previously, everything was hard-coded.

We need to test to ensure that icon is being updated, for example, with instagram.

**Comment by medhatelmasry** [comment]
There was a problem with background styling. This was fixed by Peter.
