### ISSUE TITLE
No filter and no search

### ISSUE THREAD

**Issue by medhatelmasry** [plan-your-vote/plan-your-vote-cda#78]
Filter candidates by races should be a dropdown list

**Comment by medhatelmasry** [comment]
As part of assignment 2, Peter Kim implemented filtering of candidates. This is a dropdown list that displays races.

We need to get a list of races from the backend rather than hard-coding them on the front end.

**Comment by medhatelmasry** [comment]
Filter by vice-president causes an error.

**Comment by pkim92** [comment]
Pull request #19 created to fix and grab option values dynamically.
The reason why "vice-president" option threw an error during the demo was that this option was actually not a valid option within the Candidate component's race state. (As the seed data was genericized)

**Comment by medhatelmasry** [comment]
THe only item that is added to data coming from backend regarding races is "All". This issue is resolved.
